### ISSUE TITLE
Popup doesn't appear on clicking feature in IE 11, IE10 and Edge 

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#101]
1. Please go the the app 
http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=e8a635f816554f1693282516b574dba5

2. Click on a feature (Polygon feature in this app)

3. Notice that popup doesn't appear

Note: Issue is seen in IE11, IE10 and Edge. Not in IE9
          Issue not seen on production envrionment.
          Issue is not data, data source(Hosted or Server) or feature specific.

**Comment by allisonmuise** [comment]
issue is also present on iPads

**Comment by MikeTschudi** [comment]
@ScottOppmann 
Suba also found this behavior on iPad
It appears to be related to using Dojo's iOS-style slider switch: the problem was introduced by that change's commit, and within that commit, adding or removing the switch is all that it takes to break or fix the issue

**Comment by allisonmuise** [comment]
@ScottOppmann : Considering this, how would you like us to handle this toggle? Should we go back to the check box for this release?

**Comment by ScottOppmann** [comment]
@allisonmuise @MikeTschudi - Lets grab 30 min this AM when everyone is in to review options. I can not access the maps referenced above and would like to review options collectively.

**Comment by MikeTschudi** [comment]
Dojo Mobile sets window.document.dojoClick to 'true' as part of its efforts to generate expected clicks in the mobile environment; see https://bugs.dojotoolkit.org/ticket/15878. Setting the parameter to 'false' shortly after startup appears to fix this problem, but need to test ramification of change.

**Comment by MikeTschudi** [comment]
with commit 0bd048f020d05c6aeef0f95586a674d79bcc88f4,

Tap graphic, switch OK
* iOS 8.1 iPhone 6 Safari
* iOS 8.4 iPad 3 Safari
* iOS 9 iPad Mini Safari, Chrome
* Win 7 Chrome 45, 46
* Win 7 Firefox 41
* Win 7 IE 9, 10, 11

Tap graphic OK; too small for switch to be displayed
* iOS 9 iPhone 5 Safari, Chrome
* Android 4.4 Galaxy S4 Chrome

Tap graphic OK; switch problematic--works better by sliding than tapping, but still cranky
* Android 4.1 Galaxy Tab 2 Chrome
