### ISSUE TITLE
photo attachments stretch in IE11

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#107]
doesn't happen in chrome, ff, or ie10
photos stretch to fill the viewer horizontally, but maintain their original vertical height

**Comment by MikeTschudi** [comment]
App uses the "object-fit" approach to scale image attachments into the gallery, but it's not supported in any IE (cf. http://caniuse.com/#search=object-fit)

**Comment by allisonmuise** [comment]
ok - we'll come back to this in a future release. Not sure if we'll want t o change or not.
