### ISSUE TITLE
strip whitespace from entered values

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#108]
this will resolve issues when only spaces are entered in required fields.

**Comment by MikeTschudi** [comment]
Handled via validation pattern in dijit in commit 1c3116e53a243e5db73174430bddf257ba620b78; ready for merge from branch 'trim-form-fields' into branch 'develop' when desired

**Comment by allisonmuise** [comment]
verified that required parameters with only whitespace are still marked as needing values
