### ISSUE TITLE
Help display resizes awkwardly if window resized while display is open

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-polling#110]
After page refresh and before window resize:
![image](https://cloud.githubusercontent.com/assets/2125181/10674201/8dd9e02c-78ae-11e5-8f78-5164102ac0ea.png)

After resize while help display is open:
![image](https://cloud.githubusercontent.com/assets/2125181/10674229/a7a7f84a-78ae-11e5-85ef-9d066885c207.png)

**Comment by allisonmuise** [comment]
verified
