### ISSUE TITLE
Layer's popup removed from webmap show as 'undefined' in app

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#111]
If popup is removed from the layer in webmap then popup header shows as 'undefined' in the app on AGOL 3.10

1. Go to http://localgovdev.mapsdevext.arcgis.com/home/item.html?id=bd1a770f38ab4daa9fc8d365626c466b

2. Noticed the popup feature shows as 'undefined'

3. Attached the screenshot of app created in AGOL 3.9 and AGOL 3.10

3.9 app's screenshot

![popup_twitter](https://cloud.githubusercontent.com/assets/3836616/10680939/47bec5e6-78d9-11e5-8777-d7e050d81648.PNG)

3.10 app's screenshot

![image](https://cloud.githubusercontent.com/assets/3836616/10680959/662953e8-78d9-11e5-9a23-c90da66c742a.png)

**Comment by MikeTschudi** [comment]
Fixed in commit 541aaaa0a4e05188c052898a61507c74cc89167b

**Comment by allisonmuise** [comment]
verified
