### ISSUE TITLE
In Firefox, popup doesn't open from the top when previously viewed feature was scrolled to the bottom of the comment section

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#112]
1. In firefox browser, Open the app in http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=e8a635f816554f1693282516b574dba5 Firefox
2. Click on feature (Sarah)
3. Scroll down to bottom of the page to view the comments
4. Click back button
5. Click on another feature (McDonald)
6. Notice the items didn't refresh to show popup from the top, instead it shows the comments section 

Note: issue was not seen in other browser.

**Comment by allisonmuise** [comment]
verified on qa
