### ISSUE TITLE
Please specify the 'Commenter Name Field' value is case sensitive in the hint showing in config panel

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#117]
Currently its shows the following message

'Field in a table with a geodatabase relationship to the selected feature layer for storing the name of authenticated commenters. Table must exist in map'

As per design if the 'Commenter Name Field' value is not in the same case as the Field's name in the table, then field is not populated upon social media sign in in the app.

**Comment by allisonmuise** [comment]
done
