### ISSUE TITLE
Config option for help as splash screen

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#120]
add config option (False by default) to present the help window on app load.

**Comment by MikeTschudi** [comment]
@allisonmuise: Is this option to be supported in the hosted environment or just the standalone environment?

**Comment by allisonmuise** [comment]
in both

**Comment by allisonmuise** [comment]
@MikeTschudi : Did the the updated config panel go to Ian with this change?

**Comment by allisonmuise** [comment]
related to 4664 in arcgis-js-api
