### ISSUE TITLE
Multi-line text entry setting not honored

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#121]
In the popup configuration, text fields have the option to display as single or multi-line parameters in the editing form. Regardless of this setting, Comment form parameters are displaying as single line.

@MikeTschudi : Could you do a LOE estimate for 4.1? If it's super easy and you've got the bandwidth, let's do it; otherwise I'll bump to 4.2.

**Comment by MikeTschudi** [comment]
Please double-check that the multi-line setting was saved.  In testing just now, saving the popup and then the webmap did not actually save the configuration change from single-line to multi-line.  Once I was sure that a field was configured as multi-line, it appeared as expected:
![image](https://cloud.githubusercontent.com/assets/2125181/12598420/198b382e-c43f-11e5-9515-94ebe819ef55.png)

**Comment by allisonmuise** [comment]
*Pushes button*
That was easy

closing this issue as my error
