### ISSUE TITLE
Form with Fields marked as 'required' loads with red exclamation mark

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#122]
Go to this app
http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=f1be2bf0ee9f4b0f8fd37197c744746a

1. Click on a feature 

2. Click on comment

3. Notice the fields in the form

![image](https://cloud.githubusercontent.com/assets/3836616/12653151/0a6cff16-c5a3-11e5-86af-bcfd1ebec305.png)

**Comment by MikeTschudi** [comment]
As designed:  feature service has blanks for defaults for required fields and leading-blank entries are not valid, so when comment form starts up, it flags these invalid values.  cf. #123

**Comment by allisonmuise** [comment]
Yes, this is ok
