### ISSUE TITLE
Entering a value in 'Required' field is not accepted the first time.

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#123]
Go to this app
http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=f1be2bf0ee9f4b0f8fd37197c744746a

Click on a feature

Click on comment

Enter a value in the 'Name' field and notice the field is still red. Value gets accepted upon reentering.

**Comment by MikeTschudi** [comment]
As designed:  feature service has blanks for defaults for required fields and leading-blank entries are not valid, so when user types in a required field, he/she is appending to an invalid entry that stays invalid. It's not until the field is cleared and re-typed that it becomes valid.  cf. #122

**Comment by allisonmuise** [comment]
@skrishn : Please verify that these fields have whitespace (instead of Null) as default values in these required fields

**Comment by skrishn** [comment]
Issue was reproducible with a new dataset by adding a  space in the default value for the fields that doesn't allow null values. 

Issue was also reproducible with current dataset (published a new service for testing) but there is no  space in the default value for the fields that doesn't allow null values. Current dataset could be corrupted.
