### ISSUE TITLE
Fix RtL language display issue

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#125]
1. Open a crowdsource polling app 
2. Set the browser language to arabic or hebrew (Right to left language)
3. Notice the Filter by Map toogle switch appears as below

![image](https://cloud.githubusercontent.com/assets/3836616/13269767/76cc1dc2-da3e-11e5-8ad4-485259c8cec0.png)

**Comment by allisonmuise** [comment]
@MikeTschudi : This issue is larger than the one instance mentioned above. This app is not very RtL-friendly. Let's take a look at the work CT has done with Reporter and see where else enhancements need to be made

**Comment by allisonmuise** [comment]
In RtL languages:
- [ ] Display the app logo in the right side of the header
- [ ] Display the help icon in the left corner of the header
- [ ] Display the sign in button to the right of the moved help button
- [ ] Move toggle to the left of the toggle label
- [ ] Move vote count to the left side of each list item and align them with the left margin. Text should stay aligned right. Hearts should stay on left side of number.
- [ ] In header of details for each item, move vote count to the left side of each list item and align them with the left margin. Text should stay aligned right. Hearts should stay on left side of number.
- [ ] Arrows pointing to the left indicate 'forward' in RtL languages. Arrows pointing to the right indicate 'back'. The 'Back' Arrow should be moved to the right side of the header bar and it should point right.
- [ ] Positions of Submit and Cancel buttons should be reversed
- [ ] Close X should be in the upper left corner of the help and sign in windows

**Comment by allisonmuise** [comment]
@MikeTschudi : Can we address any/all of these for 4.2?

**Comment by allisonmuise** [comment]
moving to 4.3

**Comment by allisonmuise** [comment]
verified on devext
