### ISSUE TITLE
BUG-000095610 - Commenting within the Crowdsource Polling application fails if using a feature service published via ArcGIS for Server.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#133]
Can't submit comments when services are published using ArcGIS Server and comment form contains a date field.

This app is available internally:
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=d557d6ea816c4e62955de1ad9a1b73fa

@MikeTschudi : When you are back in the office, could you evaluate to see if this is something that can be fixed for this release. If not I'll push to 4.3.

Full details will be in devtopia once Ian exports the issue.

**Comment by MikeTschudi** [comment]
Same underlying issue as #131 
Fixed via commit dc1ec27825720d436d3991eea6085eddc865778c and in release queue
@allisonmuise @iwittenmyer

**Comment by allisonmuise** [comment]
verified by @skrishn
