### ISSUE TITLE
Support for Attachments on Comments

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/crowdsource-polling#134]
User: Local Politician
Target Audience: Public 
Business Problem: He wants to engage citizens and ask for their feedback on their local bus stations. He'd like them to add comments and **photos** that his team can review. For instance, maybe their bus stop is consistently dirty or in disrepair - he'd like to see a photo.
GIS Problem: Add attachments to a table.

Let @Jiriteach and I know if you have any more questions about this use case. 

Demonstration Example: http://eaglegis.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=beca9dbae7ef42a0a0863aa1a3b6475d

![image](https://cloud.githubusercontent.com/assets/4256979/15727488/ea48fa8a-28aa-11e6-89d4-43fdda4fa8c9.png)

**Comment by MikeTschudi** [comment]
We can get implementation ideas from Crowdsource Reporter's geo-form widget; see the `_createAttachments()` function hierarchy.

**Comment by allisonmuise** [comment]
@MikeTschudi : I'm not seeing an option to add attachments as part of the form for adding related records. Should this appear automatically when attachments are enabled on the related table?

**Comment by allisonmuise** [comment]
@MikeTschudi : any thoughts on this?

**Comment by MikeTschudi** [comment]
I've only just started the design for this enhancement; I don't know enough to answer the question.

**Comment by allisonmuise** [comment]
@MikeTschudi : Please look to the design that CT used for Reporter. They have already sent the code drop with the same enhancement for that app.

**Comment by allisonmuise** [comment]
@MikeTschudi Is this in and ready for testing?

**Comment by allisonmuise** [comment]
@MikeTschudi : Can a message display when attachments are not able to be added successfully?

**Comment by MikeTschudi** [comment]
Yes, but will take a half day or so to add upload monitoring to app

**Comment by allisonmuise** [comment]
I'll put it for 5.1
