### ISSUE TITLE
Configuration option to control order of items in list

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#139]
Add a configuration option to allow records to be sorted alphabetically or by age (OID) either ascending or descending.

**Comment by MikeTschudi** [comment]
We'll need to add a template configuration item to specify the sort field when publishing the app. If undefined, no sorting.

ItemList.js builds the summary list using the function
```
/**
 * Builds the items list
 */
buildList: function () {
    array.forEach(this.items, lang.hitch(this, this.buildItemSummary));
}
```
so we can insert before the `array.forEach()` a `this.items.sort();` call referencing a compare function.

Might want to encourage user to use a field other than OID in case OIDs for deleted items are re-used by the backing store; e.g., the try-it has a SUBMITDT timestamp field.

**Comment by allisonmuise** [comment]
To maintain consistency with existing app behavior, the default behavior when no field is selected must remain consistent with the current behavior which is, I believe, sorted by OID, descending. 

OID values are not re-used when a feature is deleted, only when the service as a whole is re-published.

**Comment by MikeTschudi** [comment]
The default is the order returned by the feature service; there are no guarantees about this order.

**Comment by MikeTschudi** [comment]
@allisonmuise -- Proposed configuration UI additions in yellow:
![image](https://cloud.githubusercontent.com/assets/2125181/19732401/80f78baa-9b55-11e6-806f-b8266c10a89f.png)

**Comment by allisonmuise** [comment]
@MikeTschudi : looks good. The fields are pulled from the selected layer?

**Comment by MikeTschudi** [comment]
Yes, using standard configuration component `layerAndFieldSelector`.

The sort field can be of type esriFieldTypeSmallInteger, esriFieldTypeInteger, esriFieldTypeSingle, esriFieldTypeDouble, esriFieldTypeString, or esriFieldTypeDate.

**Comment by allisonmuise** [comment]
👍

**Comment by MikeTschudi** [comment]
Custom sort function doesn't work reliably with null attributes in Firefox 49 and IE 11.

**Comment by MikeTschudi** [comment]
Nulls and undefineds now sort before non-null/defined items

**Comment by allisonmuise** [comment]
verified in FF, C, and IE11
