### ISSUE TITLE
Limit voting to one vote per item per browser session

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#141]
When Vote button is clicked once, it currently turns blue. Additionally, modify the button behavior so that after being clicked once, clicking it again does not further increment the vote count.

Store the ID of all items that have been voted for in the current browser session. When an item is opened, check to see if it has been voted for in the current session. If it has been, load the Vote button in it's Blue, inactive state. If a vote has not been cast for the current item, loading should occur as it does now.

**Comment by ScottOppmann** [comment]
@allisonmuise - will we implement a similar solution in Reporter once we prove this out?

**Comment by allisonmuise** [comment]
@ScottOppmann : Already done. Got the Reporter code drop with the change this AM

**Comment by allisonmuise** [comment]
verified
