### ISSUE TITLE
JSAPI 3.18 breaks app for some webmaps

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-polling#147]
JSAPI's createMap function fails with a typeerror

Examples:
- out of the box with no URL params: <server>/crowdsource-polling
- <server>/crowdsource-polling/?appid=71128d0e83be41fc90a0379a36e65e53
- <server>/crowdsource-polling/?appid=51a4564410d744e28d8d289f84adfd50

using the jsdev.arcgis.com/3.18 version

**Comment by allisonmuise** [comment]
@MikeTschudi did this get addressed?

**Comment by MikeTschudi** [comment]
Resolved
