### ISSUE TITLE
back should return to previous screen

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#154]
in smartphone view:
open map view
click on a feature to open the details
click the back button

app returns you to the list instead of the map

**Comment by allisonmuise** [comment]
@MikeTschudi I'm still being returned to the list after clicking a feature on the map in smartphone view. If I open the details by clicking a feature on the map, I expect the back button to return me to the map, not the list.

**Comment by MikeTschudi** [comment]
Need to add update to go-to-map-view button inside the item details display

**Comment by allisonmuise** [comment]
verified
