### ISSUE TITLE
apply org theming

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#161]
Please manage work on this issue separate from work on other issues for 4.4.

Org-level theming options will be accessible in this JSON format:

```
{
    header: {
        background: "#337ab7",
        text: "#fff"
    },
    body: {
        background: "#FFF",
        text: "#333"
    },
    button: {
        background: "#D95F45",
        text: "#333"
    },
    logo: {
        small: "https://org.maps.arcgis.org/logo-small.png"
    }
}
```

These options will be read in to the app and applied by the same mechanism that values from defaults.js are read in until alternate values are supplied in the configuration panel. This means that there may be a disconnect between what is shown in the config panel and the app's appearance. This is ok.

Schemas for the application of these options follow:

**Comment by allisonmuise** [comment]
![10-25-2016 4-05-15 pm](https://cloud.githubusercontent.com/assets/2752195/19707550/126db2c8-9acd-11e6-87b1-9c1f7cc12618.png)

![10-25-2016 4-05-23 pm](https://cloud.githubusercontent.com/assets/2752195/19707551/14a134fc-9acd-11e6-9ead-2a6a90bbbc07.png)

![10-25-2016 4-05-29 pm](https://cloud.githubusercontent.com/assets/2752195/19707554/16219416-9acd-11e6-8fde-c3860c22496e.png)

![10-25-2016 4-05-37 pm](https://cloud.githubusercontent.com/assets/2752195/19707556/178afe96-9acd-11e6-81a2-05b5aefb70b2.png)

![10-25-2016 4-05-46 pm](https://cloud.githubusercontent.com/assets/2752195/19707557/18f159e2-9acd-11e6-8379-768882505af1.png)

![10-25-2016 4-05-53 pm](https://cloud.githubusercontent.com/assets/2752195/19707558/1a5a18aa-9acd-11e6-93c9-8b76013f4b44.png)

![10-25-2016 4-06-00 pm](https://cloud.githubusercontent.com/assets/2752195/19707562/1bcc151c-9acd-11e6-9b20-87962aca17bf.png)

![10-25-2016 4-06-08 pm](https://cloud.githubusercontent.com/assets/2752195/19707564/1d4d01c6-9acd-11e6-9e15-d4018e5e0614.png)

**Comment by allisonmuise** [comment]
CLARIFICATION:

The logo mentioned in the JSON will point to the application logo, NOT the favicon as indicated in the mockups. When a logo is specified at this level it will override the current logic for this logo. When no logo is specified, the app should use the current logic for finding a graphic for this space.

**Comment by allisonmuise** [comment]
Per AGOL team:

The config panel parameters will be connected to the org theming parameters by adding a sharedStyleProperty property to each of the affected parameters in the JSON. For example:

           {  
               "label":"Title logo:",
               "fieldName":"logo",
               "type":"string",
               "sharedThemeProperty":"logo.small",
               "tooltip":"Defaults to sample logo"
            },

**Comment by allisonmuise** [comment]
@MikeTschudi shared theme appears to be applied to all configured applications immediately. Shared theme properties should not override previously-configured colors. They should only override the default options shown in the config panel for brand new apps.

**Comment by MikeTschudi** [comment]
Added org icon via 9c654ed585fe4943a4b12644c525180e1ec05c62

**Comment by allisonmuise** [comment]
verified
