### ISSUE TITLE
hide votes and comments buttons when user doesn't have editing permissions

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#163]
(reported from Holistic)
When accessing the application while signed in to an account that does not have editing capabilities, attempting to vote or submit a comment throws a browser error. Hide these buttons when the user does not have editing permissions, including when it is a level 1 account.

**Comment by allisonmuise** [comment]
use cases where editing must be restricted:
- [ ] Authenticated AGOL user does not have editing capabilities (includes Level 1 users)
- [ ] Editing is restricted to members of a group containing the layers

None of these apply if the layer is shared with Everyone

**Comment by MikeTschudi** [comment]
Implemented to the extent of API support.  The app will continue to display an error message for attempted votes or comments from logged-in-but-not-privileged users. From API notes:
> OK, so, sounds like we have confirmed that the expected behavior for a L1 user logged in attempting to edit in a public app is that they can NOT edit. This is because they do not have the edit privilege enabled. If an Org Admin wants their L1 member to be able to edit, they should enable the edit privilege for them.

Buttons can't be hidden because there appears to be no way for the app to know if a user can vote or comment until he/she attempts the vote or comment.

**Comment by allisonmuise** [comment]
@MikeTschudi does the org supply this information when the apps starts?

**Comment by MikeTschudi** [comment]
@allisonmuise no; the information is not available until after the logged-in user attempts to access a resource for which he/she does not have access.

**Comment by MikeTschudi** [comment]
Implementation matches the Viewer implementation

**Comment by allisonmuise** [comment]
@MikeTschudi : hmmm... ok. That wasn't what I'd discused with them previously. That will hopefully make this easier for CT, too

**Comment by allisonmuise** [comment]
@MikeTschudi : Is this installed in Devext and ready for testing?

**Comment by MikeTschudi** [comment]
It's in devext, but I haven't set up convincing test cases for it yet

**Comment by allisonmuise** [comment]
@MikeTschudi When signed in as a view-only user I can't see comments that were submitted by others.

**Comment by allisonmuise** [comment]
@MikeTschudi  - the above comment is still an issue on devext. Can you fix today?

**Comment by MikeTschudi** [comment]
@allisonmuise May I have some clarification about what you're seeing, please?

Using the repro demo that you sent without logging in, I see three items.  Only the third one has comments.

When I log in using the supplied credentials, the app is not showing the "Comments" section at all--no heading, no "No comments" for the first two items, no comments text for the third item.  This is seriously wrong and I'm working on it.  But is there something else, too?

**Comment by allisonmuise** [comment]
nope, that's what I'm seeing too. Everything looks good except that the existing comments aren't displaying with the viewer account.

**Comment by MikeTschudi** [comment]
With commit 097605b1bd1c35823754d67d8025827a3dccd463, fixed comments display for signed-in view-only user.

App had been configured to turn off everything about comments for these users: add-comment button and comments display. Changed to only turn off button.

**Comment by MikeTschudi** [comment]
@allisonmuise looks good in devext

**Comment by allisonmuise** [comment]
@MikeTschudi  sure does!
