### ISSUE TITLE
post-comment period workflow

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#168]
USFS, Geonet, etc:

How to support the workflow of a defined comment period, including leaving the app live and accessible for information purposes post-comment period

**Comment by allisonmuise** [comment]
CT has done this in Reporter this release by installing a radio button pair into the configuration panel that allows the configur-er to toggle between and 'opened' and 'closed' comment period. When the 'closed' value is selected, the voting and commenting buttons are disabled, but not hidden. Clicking them pops up a window that displays a configurable message along the lines of 'Commenting is now closed'

**Comment by allisonmuise** [comment]
@MikeTschudi - note milestone :)

**Comment by MikeTschudi** [comment]
@allisonmuise, clicking on a disabled button shouldn't have any effect:  that would negate decades of UI convention and thus confuse users. 'Commenting is now closed' needs to be indicated in a different way, such as by a static message. (Why require the user to click to get this info?)  The message could be an overlay over the scrimmed buttons.

**Comment by allisonmuise** [comment]
@MikeTschudi : Perhaps a better way of stating this would have been: The function of the buttons should be changed. Rather than initiating the comment form or logging the vote, the message 'Commenting is closed' message appears.

**Comment by MikeTschudi** [comment]
@allisonmuise, wouldn't that drive you mad as a user? The app offers an action and then says, "sorry, you can't do that". Disabled buttons convey that an action is not available; a message explains why.

**Comment by MikeTschudi** [comment]
@allisonmuise, CP has two types of message box; preference for this use?

![image](https://user-images.githubusercontent.com/2125181/32066546-fef49da0-ba34-11e7-8273-757347099714.png)

![image](https://user-images.githubusercontent.com/2125181/32066564-0dc80e3e-ba35-11e7-9324-3f1be6097b32.png)

**Comment by allisonmuise** [comment]
@MikeTschudi The second - it will allow the configur-er more flexibility with the information they want to provide their users.

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@aparveen added testcase
