### ISSUE TITLE
Search by layer updates the popup panel even if the layer is not congifured in the app

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#169]
Repro steps

1.	Choose a webmap with more than one layer.

2.	In the web map setting :

        1.	Check the option ‘Search by Layer’ and choose layer(s) and the field to be searched for. 
        2.	‘Search by address’ can be checked or unchecked. 

3.	Create a polling app and configure a layer 

4.	Open the app 
       1.	Click on the search bar 
       2.	Enter a value of the layer that is configured in the web map setting. 
       3.	Make sure to search it on the layer configured in webmap setting by using the dropdown in the search bar or from the suggestions. 

Observation
      1.	Map zooms to the location
      2.	The popup panel is updated (ie: Displays the Point layer info) which shouldn’t be updated. 
      3.	Vote button is visible. When Vote is entered – it errors out as Error: Incorrect geometry type.
      4.	Comments can be submitted but comment panel doesn’t get updated with the latest comment
      5.	Gallery images can be viewed.

Noticed in Production and Devext.

**Comment by MikeTschudi** [comment]
Implemented @skrishn's idea to highlight the chosen result of a search without selecting it for the polling feature details list. Includes new ability to click on a highlighted item and, if it is in the configured polling feature layer, it opens in the polling feature details list; if not in the layer, nothing happens.

**Comment by allisonmuise** [comment]
@MikeTschudi : This issue is in the 5.2 milestone. Did you install it for 5.1?

**Comment by MikeTschudi** [comment]
Yes; missed the milestone note

**Comment by allisonmuise** [comment]
@MikeTschudi : ok, I'll move it to this milestone so that we remember to test and document it.

**Comment by allisonmuise** [comment]
@skrishn - please test. 

If the issue has been fully resolved, please close the issue, add the Verified label, and remove the Installed label.
