### ISSUE TITLE
Signing button does't show for newly configured apps unless Google signin is enabled

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#170]
- Create a new polling app and configure it

   - By default Twitter is enabled, but no sign in button is visible
   - Enable Facebook and notice no sign in button is visible
   - Enable Google plus and notice the sign in button is visilbe. 

- Click Signin button and notice only Google option is available.

**Comment by MikeTschudi** [comment]
Impossible to test on non-public network because of Facebook and Google+ callback requirements, and not reproducible on public network.
