### ISSUE TITLE
Repeat use of Search dijit for same feature yields defective display

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-polling#171]
Using the default webmap in the app, type "downtown" into the search dijit and choose the "Naperville Downtown 2030" feature from the Land Use Cases layer.  The app zooms to the feature.

In the search dijit, change the "downtown" a little without clearing it (e.g., to "downtow") and choose "Naperville Downtown 2030" again. The app appears to zoom in further and doesn't show the feature.

If you pan, you'll see that the zoomed-in display is superimposed on the regular zoom level: you'll eventually pan beyond its boundary to a normal map. The feature layer is also missing from the display.
![image](https://cloud.githubusercontent.com/assets/2125181/22750421/9dada58a-ede5-11e6-9ec3-3f8cc598ac20.png)

As a comparison, here's what the above area should look like:
![image](https://cloud.githubusercontent.com/assets/2125181/22750489/e8403aae-ede5-11e6-8e2c-76d9e08215f5.png)

If you zoom, you'll see the feature layer again.  If you search for a different item, the app behaves as expected. The problem is just with consecutive duplicate Search dijit searches that yield the same selected feature. 

Occurs with JSAPI 19 and 20dev

Attempts at a fix:
* clearing the Search dijit after the selection (no effect)
* turning off the Search dijit's autoNavigate, but then no zooming occurs for features that are not in the feature layer (e.g., from other feature layers and from the geocoder)
* map refresh after selection (no effect)

**Comment by MikeTschudi** [comment]
Appears to be caused by conflict between Search dijit's zoom to item and app's zoom to item. Changed app to skip its zoom for Search dijit results.

**Comment by allisonmuise** [comment]
@MikeTschudi : How significant is this change to the app code/functionality? We are doing certification so trying to keep a close eye on what needs testing, what changes are going in, and what their impact will be. 

At this point we are trying to limit commits to final tweaks to new functionality, showstopper bugs, and regressions.

**Comment by MikeTschudi** [comment]
Avoids defective map tiling display

**Comment by allisonmuise** [comment]
@MikeTschudi Is this going out for 5.1, or is this for 5.2?
