### ISSUE TITLE
Add support for app proxy

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#182]
add the app proxy widget to the configuration panel and then when creating a map they mixin any proxies. The Basic Viewer shows an example of using layerMixins around line 1353.

**Comment by MikeTschudi** [comment]
The proxy configuration doesn't even appear in the AGOL configuration app unless premium content is found in the helper services. Nothing in crowdsource-polling uses premium content (http://www.esri.com/software/arcgis/arcgisonline/credits); may please I have an example AGOL app configuration illustrating the problem?

**Comment by allisonmuise** [comment]
@MikeTschudi - This can been seen if you add a premium service (such as World Traffic) to the map used by the application.
http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=ff11eb5b930b4fabba15c47feb130de4

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could you please implement this change in Polling for the 5.3 release. I would need it delivered by next Wednesday - Sept 13th.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  This fix isn't working for me. I'm not getting the app proxy prompt in devext, even when the map contains the world traffic service.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam user error on my part. Got it working and it looks good!
