### ISSUE TITLE
If neither voting nor sorting fields are configured, console error and no search box atop list

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#188]
Please refer to email for the apps that has the error

**Comment by MikeTschudi** [comment]
The commit for #153 introduced bugs when no fields of a polling feature layer are configured either for voting or sorting:

1. The variable this._searchControls.itemList is only initialized if these fields are configured, yet it is later referenced whether or not they are configured. This leads to a `TypeError: Cannot read property 'id' of undefined` error in the debugging console.
2. The search box at top of list view in phone mode (#153) is not created.

**Comment by skrishn** [comment]
@MikeTschudi @allisonmuise. Thanks. Verified
