### ISSUE TITLE
filter to map extents not working - FF only

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#193]

**Comment by allisonmuise** [comment]
update: This is only reproducible on laptops that have a touch screen, when using the mouse or the touch pad. It is not reproducible when toggling the control by touching the screen.

**Comment by cosbyr** [comment]
Looked into this a little further. When looking at the click event breakpoint in Chrome, regardless of what I click on in this application or the DOJO toolkit test page, it registers **2** click events when i click anywhere on a page with the mouse. I'm leaning towards this being a browser problem.

**Comment by allisonmuise** [comment]
@cosbyr Thanks for looking into this! closing as a know issue.
@kellyhutchins - Here is what Ryan found. Not sure if this would be relevant to the config panel issues I reported.
