### ISSUE TITLE
Honor the pop-up option "Show feature attachments as links"

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-polling#195]
Attachments are always shown for the feature if they are available. It would be a useful to honor the option "Show feature attachments as links", to determine if the attachments should be displayed, similar to how the NearMe widget honors this setting.

![image](https://user-images.githubusercontent.com/6796763/34999675-5989167c-fab0-11e7-8c00-ac7dc62d155e.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

Would you like to honor this flag for the comment layer(related layer)?

**Comment by allisonmuise** [comment]
@ashishchoure yes, please

**Comment by allisonmuise** [comment]
@chris-fox This should be available now on devext. Could you take a look and close/mark this issue verified if it meets your expectations?

**Comment by chris-fox** [comment]
@allisonmuise, looks great. thanks!
