### ISSUE TITLE
Change comment period text in config panel and documentation

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#210]
![image](https://user-images.githubusercontent.com/3836616/53195223-15fbcc00-35ca-11e9-8c06-cbf5e002d157.png)

1. Change the text  occurrences 'comment' to 'feedback' in the config panel
2. Update the documentation 
- Go to https://solutions.arcgis.com/local-government/help/crowdsource-polling/get-started/configure-app/ > other options > #7 - Update the text 'reporting period' to 'feedback period'

cc @allisonmuise

**Comment by aparveen** [comment]
Verified in devext.
