### ISSUE TITLE
BUG-000115151 The Add attachment option does not appear in the Crowdsource Polling application when opened in Internet Explorer.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-polling#211]
1. Create a feature class and table with appropriate fields for the Crowdsource Polling app in ArcMap or ArcGIS Pro
2. Create a relationship class between them.
3. Publish to your hosted content in ArcGIS Online and make sure to enable attachments for the feature service. Save as a web map.
4. Create a Crowdsource Polling app using the web map. Copy the URL of the application and open it in the Internet Explorer.
5. Here's a video to see the comparison when the application was opened in IE and Chrome: https://screencast-o-matic.com/watch/cFif2LFuNu

**Notes:**

- This issue is not reproducible in Firefox, Chrome

**Testing Data:**
*Transferred to the DevTest with the bug num

- Hosted Feature layer:http://ess.maps.arcgis.com/home/item.html?id=d99c27491dcc4fdfbe36cb4ff4bd233a
- Web Map: http://arcg.is/1jbGKD
- Map Tool Web Application: http://ess.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=996e8a06af434293b6b89e13b732e8fa

Salesforce ID: BUG-000115151
Salesforce Submitter: Nur Afifah Azhar
Salesforce Submit Date: 7/04/2018 7:55 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Medium
Repro Data: (n/a)
Work Around: (n/a)
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: N/A
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by allisonmuise** [comment]
@aparveen were you able to repro this issue? It's working fine for me in both edge and IE11
