### ISSUE TITLE
css issue - chrome

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#214]
![image](https://user-images.githubusercontent.com/2752195/64562566-22473c80-d302-11e9-85eb-7e1a9707c9fb.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

We are not able to reproduce the issue. 
We tested on latest chrome browser version : **78.0.3904.70**

Could you please let us know the chrome version on which issue is reproducible.

**Comment by allisonmuise** [comment]
I'm not seeing it anymore, either

**Comment by ashishchoure** [comment]
@allisonmuise 

- We were able to reproduce the issue after changing the zoom scale of the browser. 
- We have fixed this issue at our end and it will be delivered in upcoming code drop.

**Comment by allisonmuise** [comment]
@ashishchoure Thanks!
