### ISSUE TITLE
Filter polling layer & related feature layers in map based on the selected polling feature

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#217]
When viewing the details of a polling layer feature, the map should contain only the selected feature and any features related to that feature through a relationship class. 

Features in layers that are not connected to the polling feature layer should not be filtered. The list of polling features should not be filtered.

EG: In an app where the polling layer contains transit routes and the routes are relates to stops along those routes, selecting a route from the list should hide all the routes and stops that are not related to the selected route.

This should be a Boolean configuration parameter. When true the layers should filter. The default should be False, and the behavior should match how the app currently behaves.

When this option is True, there should be an additional option to display the cyan selection color. (True by default). When this is disabled, the app should pan, zoom, and display the details as it already does, but the feature should not be highlighted in cyan.

Please tie the implementation of this to the closely related #213

**Comment by allisonmuise** [comment]
cc @RebeccaLeh

**Comment by RebeccaLeh** [comment]
Here is a sample transit dataset https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=ff2c2f3d539b41e8929309d13a133672

**Comment by allisonmuise** [comment]
@RebeccaLeh this has been installed into devext

**Comment by allisonmuise** [comment]
@ashishchoure This works great! I notice that there is a double zoom happening, though, when a feature is selected from the list. The app first zooms in a bit, and then zooms out to show the whole feature. Is there a way to do this with one zoom so that it's smoother?
https://solutions.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=01a0c4ac5632456481e5b14d9ae1d5c6

**Comment by ashishchoure** [comment]
@allisonmuise @MikeTschudi 

- The behavior of double zoom is happening because of the changes made to resolve the github issue #191
- As per the comments added in https://github.com/Esri/crowdsource-polling/issues/191#issuecomment-339497424, looks like this behavior is implemented to resolve the issue related to highlighting the feature boundaries.

Please let us know if any action is required from our side.

**Comment by allisonmuise** [comment]
@RebeccaLeh Can you take a final look at this and let me know if there's anything else that needs to be done for this release?

**Comment by allisonmuise** [comment]
verified
