### ISSUE TITLE
Filtering, part 2

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#218]
Need ability to filter specific layers using specific queries, such as road blocks that fall within a specific date range.

- each filter is applied to only one layer.

- filter(s) must be editable in the UI.

- filters do not need to be reflected in the URL.

Perhaps configure using the 'Ask for values' filters defined in the map, with a configuration toggle (off by default) that users can enable to have these filters exposed in the app (backwards compatibility)?

**Comment by allisonmuise** [comment]
Formerly part of #213 
cc @jlindemann

**Comment by ashutoshverma-ct** [comment]
@allisonmuise 

Based on the above comments, we are assuming the following points for this functionality:
1. Filters can be applied to multiple layers of the webmap  
2. In the configuration:
   - Add one parameter to allow the user to show/hide filter button (Backward compatibility)
3. In the widget: 
   - The user can define multiple filters on one or multiple layers
   - Each filter can be turned ON/OFF individually
   - One master switch to turn OFF all the filters at once (please confirm this if required)
   - Settings button for each filter to modify layer/expression/value

Let us know your thoughts on this (mockups attached)

| Description | Proposed mockups |
| - | --- |
| Adding a new button beside "Sign in" | ![image](https://user-images.githubusercontent.com/22743029/70438984-0431d980-1ab5-11ea-826e-fab7afc4bfd7.png) |
| Filters list on click of filter button (buttons to edit and enable filters) | ![image](https://user-images.githubusercontent.com/22743029/70439052-27f51f80-1ab5-11ea-94ae-5cb95525f887.png) |
| Create/Edit filter popup screen | ![image](https://user-images.githubusercontent.com/22743029/70439123-4ce99280-1ab5-11ea-85fb-32cd3ec42fef.png) |

**Comment by allisonmuise** [comment]
@ashutoshverma-ct 
I'm going to distinguish between 2 users:
 - App Configurer is the person who sets up the map and application
 - App User is the end user of the configured application

1) App configurer defines all filters. 
2) App User can only turn those filters on/off and provide the necessary values when the filter was configured with 'Ask For Values' enabled.

Due to limitations with the app config panel, I believe we would need to pre-determine how many filters could be set if the filter configuration were to take place in the app config panel. To get around this, I propose using the filter configurations from the map. 

I'm imagining something that would have a Manager style UX for the App Configurer and a Near Me style UX for the App User.

1) App configurer defines a series of filters on one or many layers in the map.
2) App configurer enables the display of these filters in the app. This can be a single checkbox parameter in the configuration panel that allows the App User to see the list of configured filters. As you described above, this should be off by default for backwards compatibility.
3) App User can tap the Filter button and then toggle on/off each of the filters. I like your idea for an 'all off'/'all on' option when more than one filter is configured. User should be prompted for values when Ask For Values is enabled on a filter.

**Comment by ashutoshverma-ct** [comment]
@allisonmuise 

Based on the above points, in the widget, we will now have only one screen for all the defined filters and a button to view the filter screen. Following are the salient points:
1. Each filter label will be layer name
2. The user can expand/collapse only those filters in which "Ask for value" is enabled
3. By default, all the filters will be applied and in the collapse state

![image](https://user-images.githubusercontent.com/22743029/70615577-aaefb480-1c32-11ea-9dc8-24ff8b5fb836.png)

**Comment by allisonmuise** [comment]
@ashutoshverma-ct 
#3 brings up a good point. Let's add a second configuration parameter for users to toggle the initial state of the filters - by default they should be applied, but this will give users an option to disable them initially

**Comment by allisonmuise** [comment]
It appears that configuring 'ask for values' filters on date fields is no longer possible. There was a bug in AGOL that allowed it for a time, but they have since fixed it.

We do need a way to configure date filters in this app:

Could you please look into using the time enabled settings on the layer? This will require two additional configuration parameters:
1) users can choose to expose the date filters (off by default)
2) users can choose to filter using start and/or end time for time enabled on two fields (start and end by default, only applied if previous option is enabled, not applicable when time is enabled on a single field)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam One other note re: the word Filter at the top of the app. We would like to make this the standard filter icon. let's re-arrange the header bar in the following order to make this look better. From left to right the icons (when relevant) should be filter, help, sign in. The burger menu options are fine as discussed.

**Comment by ashishchoure** [comment]
@allisonmuise 

We would like to discuss the date filter requirements in detail to make sure we are on same page. Could you please set up a call at your convenient time?

**Comment by allisonmuise** [comment]
@ashishchoure Would after status tomorrow work for you?

**Comment by ashishchoure** [comment]
@allisonmuise 

We can discuss the requirements after status.

**Comment by ashutoshverma-ct** [comment]
@allisonmuise 

Considering all the inputs during the discussions, here are the updated points along with the mockup:

1. Configuration: 
    - A new checkbox "Show date filters" will be added to allow a user to edit date-time fields of the widget filter

2. Widget:
   - Date filter on the webmap is not allowing "Ask for values" so this filter will not be exposed in the application filter
   - For time-enabled feature layers (mockup attached representing this case):
      - **Single Field**: Only one field will be exposed for date and time (separate for date and time picker)
      - **Two Fields**: Two fields will be exposed for date and time (separate for date and time picker)

Note: Filters defined in the map with no "Ask for values" will be not be shown in the widget

| Mockup |
|-|
| Please confirm <li>For single field: Date-time field label will be "Event date and time"<li> For two fields: labels will be "Start date and time" and "End date and time" </li> <br>Mockup also includes the filter icon in the header section|
| <img src = https://user-images.githubusercontent.com/22743029/72592983-dea4b500-3929-11ea-81e6-dbdc36f83e5b.png width = 300 align="center"> |

**Comment by allisonmuise** [comment]
@jlindemann - please review and let CT know if this looks good to you

**Comment by jlindemann** [comment]
This looks good @ashutoshverma-ct @allisonmuise I assume the second drop down is 15 minute intervals like other apps?

**Comment by ashutoshverma-ct** [comment]
@jlindemann @allisonmuise 

> I assume the second drop down is 15 minute intervals like other apps?

Yes, the second dropdown is the 15-minute interval. 
Here are the screenshots for both first and second dropdown.

![image](https://user-images.githubusercontent.com/22743029/72736585-fe570a00-3bc3-11ea-8296-44fd11a98dc7.png)

**Comment by jlindemann** [comment]
looks good

**Comment by ashutoshverma-ct** [comment]
As discussed, we need to provide a "back" button for the filter screen and match the style as shown in the below sample screenshots:

| Filter de-activated | Filter activated |
| - | - |
| ![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/22743029/76130282-1ee5f280-5fbf-11ea-8ec2-e654174a72e5.png) | ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22743029/76130286-21484c80-5fbf-11ea-9393-216de8d297f9.png) |

**Comment by allisonmuise** [comment]
verified
