### ISSUE TITLE
Related Table appears in side panel when you click on feature then click on map, when features are not related to the table

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-polling#226]
The first time you click on a feature you get the popup on the side panel, if you then click on the map then you see the comments table. The comments table is not related to the feature and should not be visible in the panel
Repo Steps
•	Click on a feature that does not have a comments table in the application (You’ll see the pop-up in the panel)
•	Click somewhere on the map (You’ll see comments table appear under the pop-up and in the panel)

**Comment by allisonmuise** [comment]
@LindsayThomas do you have a repro app?

**Comment by allisonmuise** [comment]
@LindsayThomas : see comment above

**Comment by LindsayThomas** [comment]
@jlindemann  or @chris-fox  I remember I logged these issues for the team however, I think it was one of you to that actually found the issue. Can you help Allison with a repo app?

**Comment by jlindemann** [comment]
@LindsayThomas @allisonmuise @chris-fox 
So good news it looks like this may be fixed?
Repo in current online if you follow steps above you see it:
https://www.arcgis.com/apps/CrowdsourcePolling/index.html?appid=8a4b126fa7d643c5868b262d64bc9be6&eventid=Ribfest%202020-7-23

Devext with same app and I no longer see this behavior:
https://solutions.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=f551962c91d4462baddcc4b7b36bd35b&eventid=Ribfest%202020-7-23
