### ISSUE TITLE
BUG-000133477 JQuery updates

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-polling#242]
Many customers are starting to perform static and dynamic analysis of our apps and finding issues related to dated libraries.

for Solutions apps, updating jQuery to 3.5.1 in crowdsource-reporter and crowdsource-manager appears to also require updating bootstrap, bootstrap-datepicker, and moment-with-locales because of changes to functions.

crowdsource-reporter uses

bootstrap 3.3.0 (10/2014)
bootstrap-datepicker 3.0.0 (3/2014)
moment-with-langs 2.7.0 (a predecessor of moment-with-locales that was deprecated 7/2014)
crowdsource-manager uses

bootstrap 3.3.6 (11/2015)
bootstrap-datepicker 4.17.37 (7/2015)
moment-with-locales 2.11.2 (2/2016)
I'm looking at the required call changes to the two apps using the current versions:

jQuery 3.5.1
bootstrap 4.5.2
bootstrap-datepicker 4.17.47
moment-with-locales 2.28.0

**Comment by aparveen** [comment]
I will arrange a meeting with Mike before CT starts to work on it.

**Comment by sumitzarkar** [comment]
@aparveen @skrishn @MikeTschudi 

As discussed on last call we don't see an usage of any plugins/libraries in Polling App and hence we don't see any action required on ths ticket.
