### ISSUE TITLE
Tooltip on closed comment shows html if edited with richtext

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#243]
- Create polling app
- Close feedback
- Edit 'Feedback period closed window content' with richtext 
- Hover over tooltip and it shows the richtext html 

https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=74304586e3324c62a41792db1b659c41

**Comment by ashishchoure** [comment]
@skrishn @aparveen @MikeTschudi 

- We are using **title** attribute to show the tooltip on the comment button (see below screenshot).
- **title** attribute is not capable of rendering the HTML tags (rich text contents).

![image](https://user-images.githubusercontent.com/5525972/95044111-3c696f00-06fc-11eb-988a-095d376dba34.png)

**Comment by skrishn** [comment]
@ashishchoure : Do we use tittle attribute to display tooltip for all template apps?

**Comment by skrishn** [comment]
Polling doesnt use bootstrap or jquery libraries and this is an expected behavior with title tag.
