### ISSUE TITLE
Feature Selection Graphic

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-polling#56]
When you select an item from the list in the right panel, the app zooms to the specific feature but there is no visual queue in the map which feature was selected from the list.  It is especially apparent when two features are in the same map view.  See attached image.
![crowdsource feature queue](https://cloud.githubusercontent.com/assets/2379330/7297278/6a07a5e2-e995-11e4-88a1-816fe66136b8.png)

**Comment by MikeTschudi** [comment]
main.js has a spot where the app zooms to a feature, whether the feature was selected by a click on it in the map, a click on its item in the summary list, or as a search result:
```
// Zoom to item if possible
if (item.geometry.getExtent) {
    itemExtent = item.geometry.getExtent();
}
if (itemExtent) {
    this.map.setExtent(itemExtent.expand(1.5));
} else {
    this.map.centerAndZoom(item.geometry,
        Math.min(2 + this.map.getZoom(), this.map.getMaxZoom()));
}
```
Propose to use a variant of this function from Finder/FEF;
```
/**
 * Creates an array of graphics that can be used for highlighting.
 * @param {object} geometry Geometry to be used to create graphics
 * @param {object} attributes Attributes to be used to create graphics
 * @param {object} infoTemplate Info template to be used to create graphics
 * @return {array} An array of graphics for highlighting the content;
 *        consists of a single graphic for a line or polygon and of
 *        a set of concentric circles for a point
 * @memberOf js.LGHighlighter#
 */
createHighlightGraphics: function (geometry, attributes, infoTemplate) {
    var i, highlightGraphics = [];

    if (geometry.type === "polyline") {
        // Create a line symbol using the configured line highlight color
        highlightGraphics.push(new Graphic(geometry,
            new SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,
                this.lineHiliteColor, 3),
            attributes, infoTemplate));

    } else {
        if (geometry.type === "point") {
            // JSAPI does not want NaN coordinates
            if (!geometry.x || !geometry.y || isNaN(geometry.x) || isNaN(geometry.y)) {
                return highlightGraphics;
            }

            // Create a series of concentric circle symbols using the configured line highlight color
            for (i = 0; i <= 4; ++i) {
                highlightGraphics.push(new Graphic(geometry,
                    new SimpleMarkerSymbol(
                        SimpleMarkerSymbol.STYLE_CIRCLE,
                        (i + 16) * 2.5,
                        new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,
                            this.lineHiliteColor, 3),
                        this.concentricCircleFillColor
                    ),
                    attributes, infoTemplate));
            }

        } else if (geometry.type) {
            // Create a polygon symbol using the configured line & fill highlight colors
            highlightGraphics.push(new esri.Graphic(geometry,
                new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,
                    new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,
                        this.lineHiliteColor, 3), this.fillHiliteColor),
                attributes, infoTemplate));
        }
    }

    return highlightGraphics;
}
```

**Comment by MikeTschudi** [comment]
@ScottOppmann: Current implementation style for polygons, lines, points:

Polygons: outline boundary of polygon and fill with a very light wash
![image](https://cloud.githubusercontent.com/assets/2125181/19746629/1a2838e8-9b8c-11e6-838f-82790c0b43b4.png)

Line: outline line
![image](https://cloud.githubusercontent.com/assets/2125181/19746634/1f66612c-9b8c-11e6-91b7-6c242ba1e10c.png)

Point: draw two concentric circles around point
![image](https://cloud.githubusercontent.com/assets/2125181/19746640/24ebcb6e-9b8c-11e6-971e-fbf9d932ed01.png)

**Comment by ScottOppmann** [comment]
@MikeTschudi @allisonmuise - the polygon and line selections look fine, but i wonder a bit about using two concentric circles for points.  Should we just use a single circle around a point?

**Comment by MikeTschudi** [comment]
I posted these snapshots because @skrishn mentioned that the concentric circles looked odd with a circle & dot point symbol that she'd worked with; you're not the only one wondering. :-)

**Comment by allisonmuise** [comment]
Can we stay consistent with the rest of AGOL by using a single cyan square?

**Comment by ScottOppmann** [comment]
I like that idea too.

Sent from Scott's iPhone
909-728-7082

On Oct 26, 2016, at 7:11 PM, Allison Muise <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we stay consistent with the rest of AGOL by using a single cyan square?

-

**Comment by MikeTschudi** [comment]
Changed to AGOL-style form-fitting square:
![image](https://cloud.githubusercontent.com/assets/2125181/19782617/749fd7a6-9c43-11e6-82a1-46df06fd032b.png)

**Comment by allisonmuise** [comment]
verified
