### ISSUE TITLE
Eliminate title area in help dialog box

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#58]
Text should start at the top of the box, aligned with the top of the X.

**Comment by allisonmuise** [comment]
@MikeTschudi : how much work would it be to also remove the horizontal bar that follows the text?

**Comment by MikeTschudi** [comment]
Trivial--it's the ```<hr/>``` at the end of the configuration in resources/configurationPanel.js and config/defaults.js:

```
click an item in the list to get started.</p><hr/>",
```

**Comment by allisonmuise** [comment]
sweet. thanks!
