### ISSUE TITLE
Add support for domains to comment entry form

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#62]
currently fields with coded value domains do not present a pick list of accepted values. The list should show the aliases associated with each domain value.

Fields with range domains should validate that the entered value is within the accepted range.

**Comment by MikeTschudi** [comment]
Implemented with commit a2b2170682e64ace452b83673685cc2f425eeb5b

**Comment by allisonmuise** [comment]
Fields with domains present a drop down of the domain value descriptions as expected, but the coded domain values are presented instead of the descriptions in the displayed comments:
![8-31-2015 3-37-56 pm](https://cloud.githubusercontent.com/assets/2752195/9592274/59ed7ac0-4ff6-11e5-9a76-193e5d034e5f.png)

**Comment by allisonmuise** [comment]
verified
