### ISSUE TITLE
heart graphic missing from blue bar in item details view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#70]
![4-28-2015 1-53-29 pm](https://cloud.githubusercontent.com/assets/2752195/7380032/118ee944-edae-11e4-92c6-8f853c717c07.png)

There should be a heart next to the votes count in the title area

**Comment by MikeTschudi** [comment]
Is there a repo case?  The heart will only appear if the votes field is configured.

**Comment by allisonmuise** [comment]
there wasn't a heart a year ago when this was logged.
closing this as fixed
