### ISSUE TITLE
List formatting in RtL laguages

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#80]
The list of items in the panel looks very squished in LtR languages
![7-9-2015 11-17-28 am](https://cloud.githubusercontent.com/assets/2752195/8603290/235ae8f6-262c-11e5-96e4-a05ee4dc9dea.png)

**Comment by MikeTschudi** [comment]
Current display spacing:
![image](https://cloud.githubusercontent.com/assets/2125181/9533669/77d285f2-4cc8-11e5-8813-4721497f6441.png)

**Comment by allisonmuise** [comment]
verified on local build
