### ISSUE TITLE
add app icon in app header

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#85]
app icon should be used for home screen shortcuts on mobile devices, and should not be horizontally constrained.

**Comment by MikeTschudi** [comment]
It appears that the home screen icon is not supported by some Android native browsers, but the Android Chrome supports it.

**Comment by allisonmuise** [comment]
we only support Android Chrome :)

**Comment by allisonmuise** [comment]
App icon should be same height as header bar

**Comment by allisonmuise** [comment]
verified
