### ISSUE TITLE
Add buger menu to smartphone view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#86]
Once browser is decreased to the point where 'smartphone view' takes over, display a burger icon in top right corner that, when tapped/clicked, opens a small popover menu (similar to Manager's 'Sign Out' menu)  with text links that are context-sensitive:

- List view while anonymous:
-- Sign In
-- Map View
-- Help

- Map view while anonymous:
-- Sign In
-- List View
-- Help

- List view while signed in with Twitter:
-- Map View
-- Help

- Map view while signed in with Twitter:
-- List View
-- Help

- List view while signed in with other:
-- Sign Out
-- Map View
-- Help

- Map view while signed in with other:
-- Sign Out
-- List View
-- Help

**Comment by MikeTschudi** [comment]
Help is optional (button only displayed if there's help content) in all cases.
Sign In will not appear in anonymous case if no social medium is allowed by configuration.

**Comment by allisonmuise** [comment]
yes - I forgot those two cases.

**Comment by MikeTschudi** [comment]
What tooltip should the burger have?

**Comment by allisonmuise** [comment]
It will only display on mobile devices where tooltips aren't accessible, so no tooltip necessary. If you need something for accessibility 'Menu'.

**Comment by allisonmuise** [comment]
two small changes:
- decrease the size of the outer border of the burger menu to match the width of the title bar border 
- remove the horizontal lines between menu items

**Comment by allisonmuise** [comment]
Is it possible to make the menu close when anywhere else on the screen is touched?

**Comment by allisonmuise** [comment]
verified
