### ISSUE TITLE
Re-evaluate 'link to map view' UI

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#87]
Let's start with Scott's suggestion of removing the check box and flipping the background from white (not filtered) to blue (filtered) and updating the text to reflect the action that will occur by clicking/tapping the text.

**Comment by allisonmuise** [comment]
Per this morning's meeting:
- move 'link to Map' to right side of list header
- remove button formatting
- add mobile/iOS-style toggle. 
- Text should be 'Filter list by map'
- tooltip should be 'Apply filter to list only features that are visible in the current map' (this language subject to change)

**Comment by MikeTschudi** [comment]
Adapted iPhone-style toggle switch with i18n changes; may desire CSS tweak attempts to better match app UI. Switch's label truncates with ellipses if too long to fit on one line with switch.

Usage note: linkage between map and list turned off while app is in narrow (map or list--not both) state; previous value restored when app becomes wide enough to show map and list together again.

**Comment by allisonmuise** [comment]
verified
