### ISSUE TITLE
Burger menu icon

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#92]
I think Mike M said the dojo library? had an svg graphic for the burger icon so that it isn't as fuzzy. Would also be better if the burger lines were thinner than the title font.

**Comment by MikeMillerGIS** [comment]
it is part of the fonts in infolookup or basic viewer

**Comment by allisonmuise** [comment]
Thanks @MikeMillerGIS !

**Comment by allisonmuise** [comment]
burger icon looks good
