### ISSUE TITLE
Buttons on item details page (smartphone view)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#94]
remove text from Like, Comment, and Gallery buttons (center graphics)
add Map button (use graphic and positioning from Reporter)

**Comment by MikeTschudi** [comment]
Map button replaces votes:
![image](https://cloud.githubusercontent.com/assets/2125181/10030536/f6c68c96-612c-11e5-9095-98eacd9932bc.png)
![image](https://cloud.githubusercontent.com/assets/2125181/10030539/faa0bcb0-612c-11e5-8d8d-8206bd4dac82.png)

**Comment by allisonmuise** [comment]
per conversation with Mike - this refers to map button that sits in the same row oas the likes, comments, and gallery buttons

**Comment by allisonmuise** [comment]
verified
