### ISSUE TITLE
Apply color theme to more parts of UI

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-polling#96]
Color theme currently applies to major dividing lines, selected feature, heading of selected feature's details display, and submit button

Update to apply to 
* title, sign-in, cancel, and dropdown menu text
* inversion fill upon hover over sign-in
* inversion fill for comment and gallery visible states
* dropdown menu outline
* dropdown menu and help buttons
* filter toggle 'on' background
* like, comment, map, gallery, and popup's close icons

**Comment by MikeTschudi** [comment]
Commit 72891aa67baa80d594f1ce0e52399e38e6e59984

**Comment by MikeTschudi** [comment]
Commit 72891aa67baa80d594f1ce0e52399e38e6e59984

**Comment by MikeTschudi** [comment]
Only icons remain:  dropdown menu, help, like, comment, map, gallery, and popup's close

**Comment by allisonmuise** [comment]
verified text items are now theme-colored. Modifying graphics can be revisited next release.
